config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :themes do
  resources :comments

  end
  get 'pages/home'

  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :theme
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_theme

  def create
    @comment = @comment.comments.create(params[:comment].permit(:content))
    @comment.email = email.text
    @comment.save

    if @comment.save
      redirect_to theme_path(@theme)
    else
      render 'new'
    end
  end

  private

  def find_theme
    @theme= Theme.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_params
      params.require(:theme).permit(:tittle, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/comment/_form.htm.erb
<%= form_for([@theme, @theme.comments.build]) do |f| %>
    <%= f.text_area :content %>
    <%= f.submit %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <meta name=”viewport” content=”width=device-width, initial-scale=1">
    <title>Hellocopy</title>
    <%= csrf_meta_tags %>  

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
<h1>Hellocopy</h1>
<p>¡Asegura tu copia!</p>
<p>Foro para intercambio de ideas de estudiantes de la UPOLI</p>

<br />

	<a href="https://www.facebook.com" target="blank"> 
	<%=image_tag("facebook.png") %> </a>

	<a href="https://www.twitter.com" target="blank">
	<%=image_tag("twitter.png") %> </a>

	<a href="https://www.instagram.com" target="blank">
	<%=image_tag("instagram.png") %> </a>

<div/>

app/views/themes/_form.html.erb
<%= form_for(theme) do |f| %>
  <% if theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
      <% theme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tittle %>
    <%= f.text_field :tittle %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/themes/edit.html.erb
<h1>Editing Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Show', @theme %> |
<%= link_to 'Back', themes_path %>

app/views/themes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Themes</h1>

<table>
  <thead>
    <tr>
      <th>Tittle</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @themes.each do |theme| %>
      <tr>
        <td><%= theme.tittle %></td>
        <td><%= theme.content %></td>
        <td><%= link_to 'Show', theme %></td>
        <td><%= link_to 'Edit', edit_theme_path(theme) %></td>
        <td><%= link_to 'Destroy', theme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theme', new_theme_path %>

app/views/themes/new.html.erb
<h1>New Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Back', themes_path %>

app/views/themes/show.html.erb
<p>
  <strong>Tittle:</strong>
  <%= @theme.tittle %>
</p>

<p>
  <strong>Content:</strong>
  <%= @theme.content %>
</p>

<%= render 'comment/form' %>

<%= link_to 'Edit', edit_theme_path(@theme) %> |
<%= link_to 'Back', themes_path %>